spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smmgr?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /
      suffix: .html
  http:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8
